export const routes = {
    register: process.env.VUE_APP_API_URL + 'register',
    login: process.env.VUE_APP_API_URL + 'login_check',
    refreshToken: process.env.VUE_APP_API_URL + 'refresh_token',
    ingredients: process.env.VUE_APP_API_URL + 'ingredients',
    ingredientById: id => `${process.env.VUE_APP_API_URL}ingredients/${id}`,
    tags: process.env.VUE_APP_API_URL + 'tags',
    tagById: id => `${process.env.VUE_APP_API_URL}tags/${id}`,
    drinks: process.env.VUE_APP_API_URL + 'drinks',
    drinkById: id => `${process.env.VUE_APP_API_URL}drinks/${id}`,
    fbRedirect: process.env.VUE_APP_API_URL + 'facebook/redirect',
    fbLogin: process.env.VUE_APP_API_URL + 'facebook/login',
    settings: process.env.VUE_APP_API_URL + 'settings',
    switchOnlyAvailable: process.env.VUE_APP_API_URL + 'settings/switch-only-available',
    changeOzaKey: process.env.VUE_APP_API_URL + 'settings/change-oza-key',
    apiKeys: process.env.VUE_APP_API_URL + 'api-keys',
    apiKeyById: id => `${process.env.VUE_APP_API_URL}api-keys/${id}`,
    supplies: process.env.VUE_APP_API_URL + 'ingredients/oza-supplies',
    publicRecipe: id => `${process.env.VUE_APP_API_URL}public/drinks/${id}`,
    changePasswordSettings: process.env.VUE_APP_API_URL + 'settings/change-password',
    resetPassword: process.env.VUE_APP_API_URL + 'reset-password',
    changePassword: token => `${process.env.VUE_APP_API_URL}change-password/${token}`,
    checkToken: token => `${process.env.VUE_APP_API_URL}check-token/${token}`,
    photos: id => `${process.env.VUE_APP_API_URL}drinks/${id}/photos`,
    photoById: (drinkId, photoId) => `${process.env.VUE_APP_API_URL}drinks/${drinkId}/photos/${photoId}`,
    getPhoto: (type, drinkId, photoId) => `${process.env.VUE_APP_API_URL}drinks/${drinkId}/photos/${photoId}/${type}`
};